### ISSUE TITLE
NPE in CollectEnemyData

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#367] opened 2020-04-18 21:47 UTC
## 🐞 Describe the bug

The following error is logged in Test server log

~~~~
2020-04-18 23:38:34 ERROR [verManager] StendhalRPRuleProcessor  ( 306) - error in beginTurn
java.lang.NullPointerException
        at games.stendhal.server.maps.quests.CollectEnemyData$11.getAskedItem(CollectEnemyData.java:388)
        at games.stendhal.server.entity.npc.behaviour.impl.SellerBehaviour.getAskedItem(SellerBehaviour.java:121)
        at games.stendhal.server.entity.npc.behaviour.adder.SellerAdder$1.fireRequestOK(SellerAdder.java:127)
        at games.stendhal.server.entity.npc.action.AbstractBehaviourAction.fire(AbstractBehaviourAction.java:50)
        at games.stendhal.server.entity.npc.action.BehaviourAction.fire(BehaviourAction.java:26)
~~~~

## 🌍  Environment

- Test server log

**Comment by AntumDeluge** [comment] 2020-04-18 22:57
I'm unable to reproduce this on my local server. But I added some null checks that should help if it occurs again: 5cc7480ffe25f2e053c4f1b835b12d64df4f92a8

**Comment by AntumDeluge** [comment] 2022-12-22 02:19
Closing as the issue has not resurfaced.

**Closed by AntumDeluge** 2022-12-22 02:19 UTC
Labels: type: bug, game: quest, priority: release-blocker
