### ISSUE TITLE
"Internal Error" When Trying to Access Wiki

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#175] opened 2018-08-04 19:47 UTC
*This is related to the website/wiki, not the game.*

Currently, when I try to access the wiki, I get a blank page with a banner that reads "Internal Error":
![wiki_internal_error](https://user-images.githubusercontent.com/3631473/43679972-596c61cc-97e4-11e8-90e7-e81ef3d53bdb.png)
I last tried to access on 2018-08-04 12:46 PDT.

**Comment by nhnb** [comment] 2018-08-05 16:37
This was caused by the incompatible Modern skin still lying around. I deleted all incompatible skins and the issue is fixed now.

**Closed by nhnb** 2018-08-05 16:37 UTC
Labels: Stendhal website

**Comment by AntumDeluge** [comment] 2018-08-05 21:16
Thank you @nhnb, sorry I forgot to close this.
