### ISSUE TITLE
korean translation

### ISSUE THREAD

**Issue by namjisu** [arianne/stendhal#224] opened 2019-05-26 08:15 UTC
Hello! I am a Korean who is interested in this program. 
It is sad that there is no Korean translation version as a Korean.
If you are interested in the Korean version, I will help you translate it into Korean. 
I'd appreciate it if you could be positive about the proposal.

**Comment by AntumDeluge** [comment] 2019-12-11 23:41
Closing as duplicate of #267.

**Closed by AntumDeluge** 2019-12-11 23:41 UTC
