### ISSUE TITLE
web client doesn't allow sucking down anti poison - that green stuff in a bottle

### ISSUE THREAD

**Issue by tigertoes13** [arianne/stendhal#329] opened 2020-01-26 13:29 UTC
I got bit by snake... could not drink the green stuff - just says to look at it

**Comment by nhnb** [comment] 2020-02-08 20:29
It seems to work for me.

Was that an antidote or an another item? Was it in your back or somewhere else?

**Comment by nhnb** [comment] 2020-02-23 13:43
@AntumDeluge reported the same issue in #arianne. 

We can consider this issue to be confirmed. But I cannot reproduce it myself, so I need to task some questions:

- Which version of chrome?
- Was it on local server, test server or main?
- Is there a difference between main and test (did it work in the last release)?
- Does it fail all the time. Or does it work sometimes?
- Was it on desktop or a mobile phone?
- Was the phone landscape or portrait orientation?
- Does zooming help?
- Do you get a menu on long touch?
- Does it work with a newly summoned potion?

**Comment by tigertoes13** [comment] 2020-02-24 05:00
i was on earlier today.. i think it was main game, though i signed on from website, and that has always been test... anyway, i was able to use antidotes... so main is good... how do i sign on to test in order to test if it still does what it did when i entered this to begin with... was very strange.

**Comment by tigertoes13** [comment] 2020-02-24 05:01
oh... i do not use it on a mobile device.  only pc.

**Comment by tigertoes13** [comment] 2020-02-24 05:32
i got to test server... drinking antidote works now... was so strange that day when it didnt work.. perhaps just the connection.  wish i could do the test with mobile... but i dont use the phone for gaming... i just thought though... i have a tablet that, while i dont wish to game on it, i suppose i could do testing... will think about that and perhaps give it a try... just in case you need to know, it is an android... amazon fire tablet... not sure whether i can use firefox or not.. they have their own version of browser.. perhaps that will be better, a new player in the mix...

**Comment by AntumDeluge** [comment] 2022-07-19 19:07
Going to close this as there haven't been any new complaints about it not working. I haven't experienced any recent problems.

**Closed by AntumDeluge** 2022-07-19 19:07 UTC
Labels: type: bug, component: webclient, release-blocker
